language: php

addons:
  chrome: stable
  apt:
    packages:
      - nginx

sudo: false

# Test main supported versions of PHP against latest WP. 5.2 is min supported PHP version.
php:
 # - 5.6
 # - 7.0
 # - 7.1
   - 7.2

env:
  #- WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=2.6.14
  - WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=3.4.2 RUN_E2E=1

before_script:
  - phpenv config-rm xdebug.ini
  - bash tests/bin/install.sh wc_stripe_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - bash tests/bin/run-e2e-CI.sh

#save node_modules to speed up build
cache:
      directories:
              - node_modules

after_script:
  - bash tests/bin/travis.sh after

# Specifies that Travis should create builds for master and release branches and also tags.
branches:
  only:
    - new/e2e-testing